version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    restart: always
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - db
    volumes:
      - ./app:/usr/src/app
    restart: always

  worker:
    build: ./worker
    depends_on:
      - rabbitmq
      - db
    volumes:
      - ./worker:/usr/src/worker
    restart: always
