version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
  worker:
    build: ./worker
    depends_on:
      - rabbitmq
    volumes:
      - .:/worker
